version: 2.5.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: src\CommonInfo.cs
  assembly_version: 2.0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: NuGet
- path: src\openrasta\bin\$(configuration)\*.dll
  name: dlls
- path: src\openrasta\bin\$(configuration)\*.pdb
  name: pdbs