version: 2.5.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: src\CommonInfo.cs
  assembly_version: 2.0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  parallel: true
  verbosity: minimal
artifacts:
- path: src\openrasta\bin\$(configuration)\*.dll
  name: dlls
- path: src\openrasta\bin\$(configuration)\*.pdb
  name: pdbs
