init:
  - ps: |
        $version = [version]$(cat VERSION)
        $build = $env:APPVEYOR_BUILD_NUMBER


        $branch = $env:APPVEYOR_REPO_BRANCH
        if ($branch -eq 'master') {
          $version = "$version-ci-$build"
        }
        else {
          $version = "$version-$branch-$build"
        }
        Set-AppveyorBuildVariable -Name AssemblyMajor -Value $version.Major
        Update-AppVeyorBuild -Version $version


configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: src\CommonInfo.cs
  assembly_version: $(AssemblyMajor).0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore

nuget:
  project_feed: true
  disable_publish_on_pr: true

build:
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true


artifacts:
- path: src\openrasta\bin\$(configuration)\*.dll
  name: dlls
- path: src\openrasta\bin\$(configuration)\*.pdb
  name: pdbs
