install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - ps: |
        $version = [version]$(cat VERSION)
        $build = $env:APPVEYOR_BUILD_NUMBER
        $major = $version.Major

        $branch = $env:APPVEYOR_REPO_BRANCH
        if ($branch -eq 'master') {
          $version = "$version-ci-$build"
        }
        else {
          $version = "$version-branch-$branch-$build"
        }
        Set-AppveyorBuildVariable -Name "AssemblyMajor" -Value "$major"
        Update-AppVeyorBuild -Version "$version"

  - gem install chandler
  - ps: |
        "machine api.github.com" >> "$env:USERPROFILE\.netrc"
        "  login $env:github_username" >> "$env:USERPROFILE\.netrc"
        "  password $env:github_password" >> "$env:USERPROFILE\.netrc"
        "chandler push"

assembly_info:
  patch: true
  file: src\CommonInfo.cs
  assembly_version: $(AssemblyMajor).0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration: Release

platform: Any CPU


before_build:
  - nuget restore

nuget:
  project_feed: true
  disable_publish_on_pr: true

build:
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

environment:
  github_username: serialseb
  github_password:
    secure:
      1lXaOJ0GvCAOd0O9DDvVqw2eb7TvP2jve12u3hD2g4J7RVW2c2jC5XuRFyEuduUA
artifacts:
- path: src\openrasta\bin\$(configuration)\*.dll
  name: dlls
- path: src\openrasta\bin\$(configuration)\*.pdb
  name: pdbs
